### ISSUE TITLE
Task: Add header and footer links 

### ISSUE THREAD

**Issue by cblanquera** [arkofdreams/arkofdreams.github.io#25]
In the header please add the following. Remove the circle on the social links so there's room.

 - Link to Presale
 - Link to Mystery Chest
 - Link to Mystery Pets

In the footer please add the following. 

 - Terms and Conditions
 - Privacy Policy
 - BSC scan link to AoD token
 - Link to Presale
 - Link to Mystery Chest
 - Link to Mystery Pets

**Comment by gentlyawesome** [comment]
Is this for home page?

**Comment by gentlyawesome** [comment]
Is this for home page?
